name: ev_charging_dashboard
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  firebase_core: ^3.13.0
  flutter:
    sdk: flutter
  go_router: ^15.1.1
  image_picker: ^1.1.2
  skeletonizer: ^1.4.3

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
